"""
Report generation endpoints for AQI data
"""
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import Literal
import io
import pandas as pd

from app.database.database import get_db
from app.models.user import User
from app.models.city import City
from app.models.zone import Zone
from app.utils.security import get_current_user
from app.services import aqi_service
from app.utils.response import success

router = APIRouter()


@router.get("/generate")
def generate_report(
    city: str = Query(..., description="City name"),
    report_type: Literal["daily", "weekly", "monthly"] = Query("daily", description="Report type"),
    format: Literal["json", "excel"] = Query("json", description="Response format"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Generate AQI report for a city
    
    - **daily**: Last 24 hours
    - **weekly**: Last 7 days
    - **monthly**: Last 30 days
    - **format**: json (default) or excel
    """
    
    # Calculate date range based on report type
    end_date = datetime.now(timezone.utc)
    if report_type == "daily":
        start_date = end_date - timedelta(days=1)
    elif report_type == "weekly":
        start_date = end_date - timedelta(days=7)
    else:  # monthly
        start_date = end_date - timedelta(days=30)
    
    # Get city by name
    city_obj = db.query(City).filter(City.city_name.ilike(f"%{city}%")).first()
    if not city_obj:
        raise HTTPException(status_code=404, detail=f"City not found: {city}")
    
    # Get all zones for the city
    zones = db.query(Zone).filter(Zone.city_id == city_obj.id).all()
    
    if not zones:
        raise HTTPException(status_code=404, detail=f"No zones found for city: {city}")
    
    # Collect AQI data for each zone
    report_data = []
    for zone in zones:
        history = aqi_service.get_aqi_history(
            db,
            zone_id=zone.id,
            start_date=start_date,
            end_date=end_date
        )
        
        if history:
            avg_aqi = sum(r.aqi_value for r in history) / len(history)
            max_aqi = max(r.aqi_value for r in history)
            min_aqi = min(r.aqi_value for r in history)
            
            report_data.append({
                "zone_name": zone.zone_name,
                "readings_count": len(history),
                "average_aqi": round(avg_aqi, 2),
                "max_aqi": round(max_aqi, 2),
                "min_aqi": round(min_aqi, 2),
            })
    
    report_info = {
        "report_type": report_type,
        "city": city_obj.city_name,
        "period": {
            "start": start_date.isoformat(),
            "end": end_date.isoformat(),
        },
        "zones": report_data,
        "total_zones": len(report_data),
        "generated_at": datetime.now().isoformat(),
        "generated_by": current_user.email,
    }
    
    # Return Excel file if requested
    if format == "excel":
        # Create Excel file in memory
        output = io.BytesIO()
        
        # Create DataFrame
        df = pd.DataFrame(report_data)
        
        # Create Excel writer
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            # Write summary sheet
            summary_df = pd.DataFrame([{
                'Report Type': report_type.capitalize(),
                'City': city_obj.city_name,
                'Start Date': start_date.strftime('%Y-%m-%d %H:%M'),
                'End Date': end_date.strftime('%Y-%m-%d %H:%M'),
                'Total Zones': len(report_data),
                'Generated At': datetime.now().strftime('%Y-%m-%d %H:%M'),
                'Generated By': current_user.email,
            }])
            summary_df.to_excel(writer, sheet_name='Summary', index=False)
            
            # Write zone data sheet
            if not df.empty:
                df.columns = ['Zone Name', 'Readings Count', 'Average AQI', 'Max AQI', 'Min AQI']
                df.to_excel(writer, sheet_name='Zone Data', index=False)
                
                # Auto-adjust column widths
                for sheet_name in writer.sheets:
                    worksheet = writer.sheets[sheet_name]
                    for column in worksheet.columns:
                        max_length = 0
                        column_letter = column[0].column_letter
                        for cell in column:
                            try:
                                if len(str(cell.value)) > max_length:
                                    max_length = len(str(cell.value))
                            except:
                                pass
                        adjusted_width = min(max_length + 2, 50)
                        worksheet.column_dimensions[column_letter].width = adjusted_width
        
        output.seek(0)
        
        # Generate filename
        filename = f"AQI_Report_{city_obj.city_name}_{report_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        # Return as downloadable file
        return StreamingResponse(
            output,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={
                "Content-Disposition": f"attachment; filename={filename}",
                "Access-Control-Expose-Headers": "Content-Disposition"
            }
        )
    
    # Return JSON by default
    return success(report_info)
